### ISSUE TITLE
YAML or JSON for config files

### ISSUE THREAD

**Issue by jiffyclub** [UDST/urbansim#8]
I wanted to float the idea of using [YAML](http://en.wikipedia.org/wiki/YAML) for config files instead of JSON. The only real reason for choosing YAML over JSON is that YAML is easier for humans to type, involving less quotations and brackets. On the code side things are pretty much identical. Below are examples of the same config file in JSON and in YAML. Thoughts? (No rush at all to make a decision on this.)
### JSON

``` json
{
    "model": "hedonicmodel",
    "output_table": "dset.buildings",
    "estimate_filters": [
        "units.unit_lot_size > 0",
        "units.year_built > 1000",
        "units.year_built < 2020",
        "units.unit_sqft > 100",
        "units.unit_sqft < 10000",
        "units.sale_price_flt > 30",
        "units.sale_price_flt < 1000"
    ],
    "NOTUSED": "dset.fetch_csv('nodes.csv',index_col='node_id')",
    "add_constant": true,
    "internalname": "units",
    "patsy": "I(year_built < 1940) + I(year_built > 2005) + np.log1p(unit_sqft) + np.log1p(unit_lot_size) + sum_residential_units + ave_unit_sqft + ave_lot_sqft + ave_income + poor + jobs + sfdu + renters",
    "merge": {
        "table": "dset.nodes",
        "right_index": true,
        "left_on": "_node_id"
    },
    "output_varname": "res_sales_price",
    "table": "dset.homesales",
    "table_sim": "dset.building_filter(residential=1)",
    "dep_var": "sale_price_flt",
    "dep_var_transform": "np.log",
    "output_transform": "np.exp"
}
```
### YAML

``` yaml

---
NOTUSED: dset.fetch_csv('nodes.csv', index_col='node_id')
add_constant: true
dep_var: sale_price_flt
dep_var_transform: np.log
estimate_filters:
    - units.unit_lot_size > 0
    - units.year_built > 1000
    - units.year_built < 2020
    - units.unit_sqft > 100
    - units.unit_sqft < 10000
    - units.sale_price_flt > 30
    - units.sale_price_flt < 1000
internalname: units
merge:
    left_on: _node_id
    right_index: true
    table: dset.nodes
model: hedonicmodel
output_table: dset.buildings
output_transform: np.exp
output_varname: res_sales_price
patsy: I(year_built < 1940) + I(year_built > 2005) +
    np.log1p(unit_sqft) + np.log1p(unit_lot_size) +
    sum_residential_units + ave_unit_sqft + ave_lot_sqft
    + ave_income + poor + jobs + sfdu + renters
table: dset.homesales
table_sim: dset.building_filter(residential=1)
```
